name: Run Playwright Tests

on:
  push:
    branches:
      - main  # Adjust this to your default branch or any other branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensure this is the latest version
        with:
          node-version: '20'  # Set the Node.js version to 20

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test  # Run the Playwright tests here