name: Run Playwright Tests and Deploy

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start the server
        run: npx http-server ./ -p 5500 &

      - name: Run Playwright tests
        run: npx playwright test

  notify-pages:
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass

    steps:
      - name: Confirm tests passed
        run: echo "Playwright tests passed. GitHub Pages deployment will proceed."



















#version-1
# name: Run Playwright Tests

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '20'

#     - name: Install dependencies
#       run: |
#         npm install

#     - name: Install Playwright Browsers
#       run: |
#         npx playwright install --with-deps

#     - name: Install http-server
#       run: |
#         npm install --save-dev http-server

#     - name: Start the server
#       run: |
#         npx http-server ./ -p 5500 &  # Start the server in the background

#     - name: Run Playwright tests
#       run: |
#         npx playwright test  # Run the Playwright tests
